---
- name: Install Developer CLI Tools via Homebrew
  community.general.homebrew:
    name:
      - git
      - go
      - yarn
      - vim
      - warp
      - gh
      - fzf
    state: present
  tags: dev-tools

- name: Install Developer Applications via Homebrew Cask
  community.general.homebrew_cask:
    name:
      - iterm2
      - spotify
      - gimp
      - zoom
      - virtualbox
      - vagrant
      - utm
      - firefox
    state: present
  tags: dev-tools

- name: Check if Vim config exists
  ansible.builtin.stat:
    path: "{{ ansible_env.HOME }}/.vim_runtime"
  register: devtools_vim_runtime_check
  tags: dev-tools

- name: Clone Vim config repository
  ansible.builtin.git:
    repo: https://github.com/johnstamp/vimrc.git
    dest: "{{ ansible_env.HOME }}/.vim_runtime"
    version: master
    update: false
  when: not devtools_vim_runtime_check.stat.exists
  tags: dev-tools


- name: Install Vim config
  ansible.builtin.command: sh {{ ansible_env.HOME }}/.vim_runtime/install_awesome_vimrc.sh
  args:
    creates: "{{ ansible_env.HOME }}/.vimrc"
  when: not devtools_vim_runtime_check.stat.exists
  changed_when: true
  tags: dev-tools
