---
- name: Install Developer CLI Tools via Homebrew
  homebrew:
    name:
      - git
      - go
      - yarn
      - vim
      - warp
      - gh
    state: present
  tags: dev-tools

- name: Install Developer Applications via Homebrew Cask
  homebrew_cask:
    name:
      - iterm2
      - spotify
      - gimp
      - zoom
      - virtualbox
      - vagrant
      - utm
      - firefox
    state: present
  tags: dev-tools

- name: Install Vim config (johnstamp/vimrc)
  stat:
    path: "{{ ansible_env.HOME }}/.vimrc"
  register: vimrc_check
  tags: dev-tools

- name: Clone and install Vim config
  shell: |
    git clone https://github.com/johnstamp/vimrc.git ~/.vim_runtime &&
    sh ~/.vim_runtime/install_awesome_vimrc.sh
  when: not vimrc_check.stat.exists
  tags: dev-tools
