---
- name: Install Visual Studio Code via Homebrew Cask
  community.general.homebrew_cask:
    name: visual-studio-code
    state: present
  tags: vscode

- name: Install VS Code extensions
  ansible.builtin.command: code --install-extension {{ item }}
  args:
    creates: "{{ ansible_env.HOME }}/.vscode/extensions/{{ item }}-*"
  loop:
    - ms-vscode.vscode-typescript-next
    - James-Yu.latex-workshop
    - vscodevim.vim
    - ms-azuretools.vscode-docker
    - ms-kubernetes-tools.vscode-kubernetes-tools
    - redhat.vscode-yaml
    - ms-vscode-remote.remote-containers
    - ms-python.python
    - rust-lang.rust-analyzer
  tags: vscode

- name: Install Obsidian via Homebrew Cask
  community.general.homebrew_cask:
    name: obsidian
    state: present
  tags: obsidian

- name: Ensure Obsidian plugin directory exists
  ansible.builtin.file:
    path: "{{ lookup('env', 'HOME') }}/.obsidian/plugins"
    state: directory
    mode: '0755'
  tags: obsidian

- name: Install Obsidian Excalidraw Plugin
  ansible.builtin.git:
    repo: "https://github.com/zsviczian/obsidian-excalidraw-plugin.git"
    dest: "{{ lookup('env', 'HOME') }}/.obsidian/plugins/obsidian-excalidraw-plugin"
    version: master
    update: false
  tags: obsidian

- name: Install Obsidian Git Plugin
  ansible.builtin.git:
    repo: "https://github.com/denolehov/obsidian-git.git"
    dest: "{{ lookup('env', 'HOME') }}/.obsidian/plugins/obsidian-git"
    version: master
    update: false
  tags: obsidian

- name: Install Obsidian Vimrc Support Plugin
  ansible.builtin.git:
    repo: "https://github.com/esm7/obsidian-vimrc-support.git"
    dest: "{{ lookup('env', 'HOME') }}/.obsidian/plugins/obsidian-vimrc-support"
    version: master
    update: false
  tags: obsidian

- name: Install WebStorm via Homebrew Cask
  community.general.homebrew_cask:
    name: webstorm
    state: present
  tags: webstorm
