- name: Setup MacBook for Development
  hosts: localhost
  connection: local
  roles:
    - homebrew
    - zsh
    - devtools
    - rust
    - python
    - node
    - editors
    - latex
    - docker
    - { role: jvmtools, tags: jvmtools }
