---
- name: Ensure Zsh is installed
  community.general.homebrew:
    name: zsh
    state: present
  tags: zsh

- name: Check if Oh My Zsh is installed
  ansible.builtin.stat:
    path: "{{ ansible_env.HOME }}/.oh-my-zsh"
  register: zsh_ohmyzsh_check
  tags: zsh

- name: Download Oh My Zsh installer
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh
    dest: /tmp/ohmyzsh-install.sh
    mode: '0755'
  when: not zsh_ohmyzsh_check.stat.exists
  tags: zsh

- name: Install Oh My Zsh
  ansible.builtin.command: sh /tmp/ohmyzsh-install.sh
  environment:
    RUNZSH: "no"
  args:
    creates: "{{ ansible_env.HOME }}/.oh-my-zsh"
  when: not zsh_ohmyzsh_check.stat.exists
  tags: zsh

- name: Create base .zshrc if not exists
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/.zshrc"
    state: touch
    mode: '0644'
  tags: zsh
