---
- name: Check if Homebrew is installed
  ansible.builtin.stat:
    path: /opt/homebrew/bin/brew
  register: homebrew_check
  tags: always

- name: Install Homebrew if missing
  ansible.builtin.shell: >
    /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
  args:
    creates: /opt/homebrew/bin/brew
  when: not homebrew_check.stat.exists
  tags: homebrew

- name: Ensure Homebrew is in the PATH
  ansible.builtin.lineinfile:
    path: "{{ ansible_env.HOME }}/.zshrc"
    line: 'eval "$(/opt/homebrew/bin/brew shellenv)"'
    state: present
  when: not homebrew_check.stat.exists
  tags: homebrew
