---
- name: Check if NVM is installed
  ansible.builtin.stat:
    path: "{{ ansible_env.HOME }}/.nvm/nvm.sh"
  register: node_nvm_check
  tags: node

- name: Download NVM installer
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.4/install.sh
    dest: /tmp/nvm-install.sh
    mode: '0755'
  when: not node_nvm_check.stat.exists
  tags: node

- name: Install NVM
  ansible.builtin.command: bash /tmp/nvm-install.sh
  args:
    creates: "{{ ansible_env.HOME }}/.nvm/nvm.sh"
  when: not node_nvm_check.stat.exists
  tags: node


- name: Add NVM to shell
  ansible.builtin.blockinfile:
    path: "{{ ansible_env.HOME }}/.zshrc"
    block: |
      export NVM_DIR="$HOME/.nvm"
      [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
      [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"
    marker: "# {mark} ANSIBLE MANAGED BLOCK: NVM"
  tags: node

- name: Install Node.js LTS
  ansible.builtin.shell: |
    source ~/.zshrc && nvm install --lts && nvm use --lts
  args:
    executable: /bin/zsh
  changed_when: false
  tags: node
